In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
from sklearn.utils import shuffle

In [5]:
data = pd.read_csv(r"D:\datasets\student grade.csv")

In [6]:
data

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
390     MS   M   20       U     LE3       A     2     2  services  services   
391     MS   M   17       U     LE3       T     3     1  services  services   
392     MS   M   21       R     GT3       T     1     1     other     other   
393     MS   M   18       R     LE3       T     3     2  services     other   
394     MS   M   19       U     LE3       T     1     1     other   at_home   

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0    ...      4        3      4     1     1      3        6   5   6   6  
1    ...      5        3      3     1     1      3        4   5   5   6  
2    ...      4        3      2     2     3      3       10   7   8  10  
3    ...      3        2      2     1     1      5        2  15  14  15  
4    ...      4        3      2     1     2      5        4   6  10  10  
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..  
390  ...      5        5      4     4     5      4       11   9   9   9  
391  ...      2        4      5     3     4      2        3  14  16  16  
392  ...      5        5      3     3     3      3        3  10   8   7  
393  ...      4        4      1     3     4      5        0  11  12  10  
394  ...      3        2      3     3     3      5        5   8   9   9  

[395 rows x 33 columns]

In [7]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

In [8]:
predict = "G3"

In [9]:
x = np.array(data.drop([predict], 1))

C:\Users\divay\AppData\Local\Temp/ipykernel_6892/3114434887.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = np.array(data.drop([predict], 1))


In [10]:
y = np.array(data[predict])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.2)

In [13]:
linear_regression = LinearRegression()

In [14]:
linear_regression.fit(xtrain, ytrain)

LinearRegression()

In [15]:
accuracy = linear_regression.score(xtest, ytest)

In [16]:
print(accuracy)

0.8070444451225645


In [17]:
prediction = linear_regression.predict(xtest)

In [19]:
for i in range(len(prediction)):
    print(prediction[x], xtest[x], [[ytest[x]]])

[[10.78026259 12.64884975 16.32337917 13.1456988  12.64884975]
 [10.78026259 10.78026259 16.32337917 13.1456988   8.79140267]
 [ 7.25310647 16.25427882 16.32337917  8.54221253  8.3745023 ]
 ...
 [ 8.3745023  16.25427882  8.73022149  8.54221253  8.54221253]
 [13.23276087 12.05004277  8.73022149 13.1456988  13.1456988 ]
 [16.25427882 11.84420878  8.73022149 13.1456988  10.78026259]] [[[12 11  2  0  0]
  [13 12  1  0 20]
  [16 16  2  0  2]
  [14 13  2  0  4]
  [13 12  1  0 20]]

 [[12 11  2  0  0]
  [12 11  2  0  0]
  [16 16  2  0  2]
  [14 13  2  0  4]
  [ 7 10  3  1  0]]

 [[ 8  8  1  1  4]
  [15 16  3  0  7]
  [16 16  2  0  2]
  [10  9  2  0  0]
  [ 8  9  2  0  2]]

 ...

 [[ 8  9  2  0  2]
  [15 16  3  0  7]
  [ 9  9  1  0  6]
  [10  9  2  0  0]
  [10  9  2  0  0]]

 [[12 13  2  0 14]
  [11 12  2  0 12]
  [ 9  9  1  0  6]
  [14 13  2  0  4]
  [14 13  2  0  4]]

 [[15 16  3  0  7]
  [11 12  1  0  2]
  [ 9  9  1  0  6]
  [14 13  2  0  4]
  [12 11  2  0  0]]] [[array([[12, 12, 17, 13, 12

 [16.25427882 11.84420878  8.73022149 13.1456988  10.78026259]] [[[12 11  2  0  0]
  [13 12  1  0 20]
  [16 16  2  0  2]
  [14 13  2  0  4]
  [13 12  1  0 20]]

 [[12 11  2  0  0]
  [12 11  2  0  0]
  [16 16  2  0  2]
  [14 13  2  0  4]
  [ 7 10  3  1  0]]

 [[ 8  8  1  1  4]
  [15 16  3  0  7]
  [16 16  2  0  2]
  [10  9  2  0  0]
  [ 8  9  2  0  2]]

 ...

 [[ 8  9  2  0  2]
  [15 16  3  0  7]
  [ 9  9  1  0  6]
  [10  9  2  0  0]
  [10  9  2  0  0]]

 [[12 13  2  0 14]
  [11 12  2  0 12]
  [ 9  9  1  0  6]
  [14 13  2  0  4]
  [14 13  2  0  4]]

 [[15 16  3  0  7]
  [11 12  1  0  2]
  [ 9  9  1  0  6]
  [14 13  2  0  4]
  [12 11  2  0  0]]] [[array([[12, 12, 17, 13, 12],
       [12, 12, 17, 13, 10],
       [ 8, 15, 17,  0, 10],
       ...,
       [10, 15, 10,  0,  0],
       [12, 11, 10, 13, 13],
       [15, 11, 10, 13, 12]], dtype=int64)]]
[[10.78026259 12.64884975 16.32337917 13.1456988  12.64884975]
 [10.78026259 10.78026259 16.32337917 13.1456988   8.79140267]
 [ 7.25310647 16.2